### ISSUE TITLE
missing module

### ISSUE THREAD

**Issue by SpiGAndromeda** [perfaram/Haauti#1]
Hi,

a module seems to be missing:
`import PullRefreshableScrollView` results in a `No such module 'PullRefreshableScrollView'`error.
Libraries are imported via pod.

**Comment by perfaram** [comment]
The README.md says :

> Run `pod install`, and fetch a copy to ./Libs/[PullRefreshableScrollView](https://github.com/perfaram/PullRefreshableScrollView).

So : the missing lib can be downloaded by following the link just above. It's https://github.com/perfaram/PullRefreshableScrollView, just in case. And as written in the README, you're supposed to put it in the ./Libs folder, relative to the .xcworkspace file.
